---
title: 'Career Planning'
author: Ben Harden
date: '2021-05-05'
level: 3
slug: []
categories: []
tags: []
draft: no
---

Now that we've had a chance to reflect broadly on our experiences, and made some contacts in the field, this level will ask you to transition from reflection and initial contacts to planning.

To do this, we are going to develop an [Individual Development Plan](https://myidp.sciencecareers.org/Home/About) (IDP) and review it together. These plans have been beneficial for many folks who have developed them. Even if it doesn't turn out to be super useful in the long run, my hope is that the process of reflection required to set one up will be a valuable exercise in itself.

There is an online tool that you can use to develop you plan which you can access at the following address:

https://myidp.sciencecareers.org/

You should work through the various steps of self assessment, career options, and planning to complete you IDP. Please let me know how I can assist along the way. Once you are done, we should meet to review your responses and reflect on what the process showed you about yourself and your future plans.