---
title: 'Making a Better Presentation'
author: Ben Harden
date: '2021-05-05'
level: 2
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/NjEyOTIyMzMyOTk2/a/NjEyOTIyMzMzMDQz/details
---

Your goal in Level 2 to is to deliver a solid research introduction presentation that organizes ideas from broad context to specific regional details and builds towards clear questions that you are hoping to answer. Again, your class project presentation is a group effort with each presenter taking 2-3 mins for a maximum of 8 mins. Your talk should cover the following:

* Key scientific and regional background information
* What is known and not known about your topic
* What question(s) you will be seeking to answer
* What you research plan is for answering those questions

## Level 2 Expectations

If you're at Level 2, you already know how to make a slide deck with some bullets under a header with one image per slide. You'd also be pretty comfortable presenting from this slide deck, covering each bullet in turn. What we'd like to do here is to really create a focused presentation that moves from broad context to specific details and ends with a really clear and logical motivation and series of questions for your research.

For a Level 2 presentation, I'm expecting to see:

* A well thought-out progression from big ideas to specific details. Don't forget to cover all the W's: What, where, when, why. For example, if my topic were extreme wind events in New England I'd probably want to make sure I cover:
  + What an extreme wind event is
  + How they form and how frequent they are
  + Where they typically strike in New England
  * What region we are going to look at specifically
  + How we are going to measure them
  + What questions we are going to try and answer
  
* A clear statement early in the presentation about why we should care about the topic. How does it impact people or a broader ecosystem?

* Fewer words on each slide - possibly just bullet-point words not statements

* Clear and relevant images - remember, slides should be a *visual aid*. This means they should support the words you are saying and not distract from them

* Presentation from a cue card or memory

* A reference slide at the end listing your bibliography

* You can use a template slide deck