---
title: "Storytelling"
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 2
slug: []
categories: []
tags: []
draft: no
---

Storytelling is something you hear referred to all the time when it comes to the theory of Environmental/Science communication. But just saying that your communication strategy should incorporate storytelling elements isn't really enough, we need to understand what that means and what impacts different kinds of stories can have. That's what this module will be all about.

## Reading

Let's get started by looking at some readings on storytelling theory. 

### Basic Plots

The following video explains a theory popularized by Christopher Booker in his 2004 book: The Seven Basic Plots: Why We Tell Stories. Booker was certainly not the first to talk about familiar patterns in stories, but this is the jumping off point we will use. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/_AXTEjesFPs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

You can read more descriptions of these plots in [this article](https://www.how-to-write-a-book-now.com/basic-plots.html) which also includes 2 extra plots that Booker doesn't find gratifying for whatever reason ("Mystery" and "Rebellion Against 'The One'). 

### Shapes of Stories

We can also imagine stories not just as a series of happenings to and decisions by a protagonist, but alos in terms of the emotional highs and lows explicit in the story. 

Kurt Vonnegut  popularized the idea that we can think about the shapes of stories. Watch the short lecture below where he describes this theory.

<iframe width="560" height="315" src="https://www.youtube.com/embed/oP3c1h8v2ZQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In addition, read [this article](https://www.theatlantic.com/technology/archive/2016/07/the-six-main-arcs-in-storytelling-identified-by-a-computer/490733/) in The Atlantic summarizing [this paper](The_emotional_arcs_of_stories_are_dominated_by_six.pdf) wherein the author's tried to quantify the theories of story shape laid out by Kurt Vonnegut and come to pretty similar conclusions.

## Example stories

Below are some stories about the environment - what would your answers be to the questions below?

* What is key climate topic is being addressed?
* What type of story is this story? Is the story wrapped up by the end of the piece?
* Who are the characters who are taking action? What are they doing?
* What elements of effective communication that we explored in the previous module are on display here? What is less effective about the mode of delivery?
* How could you tell this story differently?

### Story 1

<iframe width="560" height="315" src="https://www.youtube.com/embed/nNcX8j3gJDw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Story 2

<iframe width="560" height="315" src="https://www.youtube.com/embed/FX7rk9PWZWE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Story 3

<iframe width="560" height="315" src="https://www.youtube.com/embed/nYlnoxgqEWo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Story 4

<iframe width="560" height="315" src="https://www.youtube.com/embed/iXt0rQNlhuM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


# Writing for Voice

First, some example radio stories to get you thinking about what kinds of things you can do with voice in storytelling.

## Stories

### Flag Design

This story is an [early episode](https://99percentinvisible.org/episode/episode-06-99-symbolic/) of Roman Mars' [99% Invisible](https://99percentinvisible.org/) podcast. It's fast-paced and intricately cut together and demonstrates some key features of grabbing people's attention and making clear descriptions of things the audience can't see.

<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/17733995&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>

### How Many Trees?

A pretty straight [science radio story from NPR](https://www.npr.org/sections/goatsandsoda/2015/09/02/436919052/tree-counter-is-astonished-by-how-many-trees-there-are) which shows us some things about working with numbers and laying out a science mystery story.

<iframe src="https://www.npr.org/player/embed/436919052/436966850" width="100%" height="290" frameborder="0" scrolling="no" title="NPR embedded audio player"></iframe>

### Glowing Orbs

Nate DiMeo has a podcast call [The Memory Palace](https://thememorypalace.us) which is short stories told artfully about history. In [this episode](https://thememorypalace.us/the-glowing-orbs/) he talks about John Glenn's mission to space and the mystery he found along the way. It is slow-paced, poetic and demonstrates a different kind of vocal performance to the stories above.

<audio controls>
  <source src="Episode61_GlowingOrbs_edited.mp3" type="audio/mp3">
</audio>

## Writing for Voice

Remember, good writing is good writing regardless of the format. There's more similar than different between writing for radio and writing for other mediums. That said, here are some tips for effective radio writing.

* **Write like you speak**: to make it personal and intimate, you have to sound like a real person using real words and expressions that people use in everyday life. One way to do this when writing a radio piece is just to talk about your topic to a friend and record what you say (including the bits where they ask you to explain what you mean when you use complicated language). You canthen transcribe that and use it as a basis for the kinds of language and sentence structure they might use for your story. Its not about mimicking your natural tenancies exactly, its more about using these to design this “best version” of you for radio.

* **Use short sentences**: run-ons, big clauses, subject a long way from the start of the sentence - all of these things make listening to someone difficult. Keep it to one idea per sentence. In the end, this is not bad advice for writing more generally anyway.

* **Use concise, vivid imagery**: You can't use pictures so use the audiences imagination to generate scene and a sense of place. Tap into common imagery and use the diversity of peoples imaginations to your advantage.

* **Write in a logical simple order**: The listener can't go back and reread what you wrote so if they get confused along the way then they'll stay that way.

* **Grab their attention**: You wont always have everyone's full attention – listeners are often driving, doing the dishes, having a conversation etc. You have to grab peoples’ attention and then sustain it by laying out a story in an entertaining and logical manner. Sign-posting can also be effective.

* **Make it personal**: Radio is like having someone talking directly to you. Remember to write like you are talking to just one person and not an audience-filled room.

