---
title: "Storytelling"
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 1
slug: []
categories: []
tags: []
draft: no
---

Storytelling is something you hear referred to all the time when it comes to the theory of Environmental/Science communication. But just saying that your communication strategy should incorporate storytelling elements isn't really enough, we need to understand what that means and what impacts different kinds of stories can have. That's what this module will be all about.

## Reading

Let's get started by looking at some readings on storytelling theory. 

### Basic Plots

The following video explains a theory popularized by Christopher Booker in his 2004 book: The Seven Basic Plots: Why We Tell Stories. Booker was certainly not the first to talk about familiar patterns in stories, but this is the jumping off point we will use. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/_AXTEjesFPs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

You can read more descriptions of these plots in [this article](https://www.how-to-write-a-book-now.com/basic-plots.html) which also includes 2 extra plots that Booker doesn't find gratifying for whatever reason ("Mystery" and "Rebellion Against 'The One'). 

### Shapes of Stories

We can also imagine stories not just as a series of happenings to and decisions by a protagonist, but alos in terms of the emotional highs and lows explicit in the story. 

Kurt Vonnegut  popularized the idea that we can think about the shapes of stories. Watch the short lecture below where he describes this theory.

<iframe width="560" height="315" src="https://www.youtube.com/embed/oP3c1h8v2ZQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In addition, read [this article](https://www.theatlantic.com/technology/archive/2016/07/the-six-main-arcs-in-storytelling-identified-by-a-computer/490733/) in The Atlantic summarizing [this paper](The_emotional_arcs_of_stories_are_dominated_by_six.pdf) wherein the author's tried to quantify the theories of story shape laid out by Kurt Vonnegut and come to pretty similar conclusions.

## Exercise

Clearly the above theories are intertwined and talk to us about the variety with have in telling stories and the emotions they can elicit.

To test your understanding of this, you should pick a favorite film, book, comic, TV show... and create a visual display of the story that includes:

* A suitable image to illustrate your chosen story
* (If you think the class wont be familiar with your story) two or three sentences describing the plot/main idea
* A description of which of the seven (nine) stories your story best aligns with and why.
* An graph that describes the "shape of the story".

You should post this display on the wall of the classroom in a designated spot so we can all see each others' work.

Don't forget to reflect on this process by filling in an exit tickey below.
