---
title: "Introduction to Reading Papers"
author: Ben Harden
date: '2021-05-05'
level: 1
slug: []
categories: []
tags: []
draft: no
---

Scientific papers are technical documents written by, and for, scientists in a particular field documenting the research they undertook and the results and conclusions they arrived at.

They can be daunting to read and no one is recommending you start at the beginning and slog your way to the end. The key thing is to know *why* you are reading the paper in the first place. Have a goal in mind that will help you focus on a particular section or message.

You could be reading the paper because:

- You want to find out the importance of the field or want to know what is currently known about the topic (most of which can be found in the introduction)

- You are looking for more similar papers to give you an overview of the field (also the introduction)

- You want a quick look at the what they found (abstract, conclusions)

- You need to check or reproduce a method (methods)

- You want to scrutinize the data they are presenting or understand it for use in another project (results)

- You want want to understand where the unknowns in the field are (introduction, discussion)

This level contains a selection of resources to help you to read scientific papers that will be useful to your project. Another big resource will be your peers - many of you will have skills and specific tricks on this so I encourage you to share with each other. 

## Reading a paper

Here are some resources to read about how to read papers.

* An overview of a research paper and how you might go about reading it

 <iframe src="intro_to_papers.pdf" width="100%" height="700"></iframe>
 
* A good overview of reading a paper by Dr Cassidy D'Aloia
 
<iframe src="paper_guide.pdf" width="100%" height="700"></iframe>
  
* Some [good insights](https://www.sciencemag.org/careers/2016/03/how-seriously-read-scientific-paper) from scientists about how they (really) read papers.

### Homework

Show me you can apply this information by choosing a paper that your mentor has given you in the last couple of weeks and doing the following:

* Decide and write down what you goal is in reading the paper

* Write down which sections of the paper you focused your reading on in order to get the information you needed

* Write a few sentence summary of the information that the paper told you
