---
title: About
author: Ben Harden
date: '2023-06-04'
slug: []
categories: []
tags: []
draft: no
---

The PEP class is built to help prepare you for the work you will be doing this summer and beyond. This includes allowing you to:

- Build your knowledge and research skills in oceanographic and environmental science topics
- Understand yourself and the Woods Hole community you are becoming a part of

## Class Philosophy

Before I get to details, I want to start by laying out my philosophy for this class. 

You are all coming to this class with different experiences. Some of you have had previous research opportunities, some none. Others will have been exposed to coding skills, many will not. Some of you will be environmental science majors, while for others this will be a new topic to grapple with. Some of you will be adept at telling stories about your work, others will be starting out on this journey. 

Regardless of your previous experiences, you all have strengths to bring to the table. You all have a responsibility to keep your eyes open for your peers who are struggling and help them out. This class is a **collaborative space** so that everyone can grow their skills and understanding as much as possible. No one succeeds whilst someone else fails. We all grow together.

The scheduled class hours will be used to introduce central concepts to the whole class as well as give you structured time to work on particular skills you would like to develop.

Given your varied backgrounds and experiences, I will also be taking a **growth-based** approach to assessment. We will conference throughout the class to determine both your strengths and areas that you would like to grow in. This will allow us to set goals together for your success.

I value feedback and self-reflection. You will be given many opportunities to let me know how you are getting on, what you are understanding, and what you have questions about. This will help you track your progress and will help me understand how best to help you and your fellow students. For the duration of the PEP class, you are my primary professional activity so feel empowered to contact me if you have any questions or concerns.

Finally, remember throughout: you belong here at PEP and in the Woods Hole community. The PEP staff are here to support you and help you be successful.

## What I expect from you

I hope you will see this class as more than simply a requirement to gain a grade for college credit. It should be a useful tool for you to advance your thinking and skills around possible careers in environmental sciences. It should be directly relevant to the work you will be doing this summer as well as building a broader tool set for many possible avenues to come after you leave.

I expect you to use your time in the PEP class effectively. The class will give you lots of opportunities to work when and how you like, but we do expect you to engage with all aspects. The main class time will be 9-12 on Mondays with an additional session Tues evenings from 5-7 for professional talks and workshops. In addition to these class time, we expect you to work an additional 2-4 hours a week to complete assignments. This means that work at the weekend is also likely. Use your peers as a support network for things you are finding hard and to keep you accountable. 

I welcome your feedback (and will ask for it frequently) so please let me know how you are getting on and what isn't sticking and I will try and help you out. Please also let me know how long the classwork is taking you so we can make sure we are giving you space to grow without overloading you. Again, the growth-based format should allow us to tailor the work expectations to your goals.

## What you can expect from me

I will be available for immediate feedback and discussion during the class periods on Monday and Thursdays. Please speak up if you need my support, but be patient as we try to meet the needs of the whole PEP cohort. If there are enough questions or interest in a particular topic then we will arrange small group instruction.

Outside the class window I will also be available to answer questions and give feedback until 7pm any day except Saturdays. Please contact me through Slack and I will get back to you as soon as I am able. Again, please be patient, but persistent. Remember, your peers will often be a great resource for you - please work together if you like, but remember to only submit your own work (see policy on academic accuracy in the syllabus).

## Class Structure

OK, so on to the nuts-and-bolts. 

We are going to be mostly thinking about skills that we think are going to be most useful to you in your research this summer and your broader career in the coming years. These will include:

* Reading papers and developing a research bibliography
* Data visualization through coding
* Spoken presentation skills
* Poster making
* Broadening understanding of the science undertaken in Woods Hole
* Science storytelling

Each of these topics will come with opportunities for you to show me where where you are and give you new insights to help you develop those skills.

In addition to assignments aimed at developing your skills in each of these areas, you will also have a chance to pick one specialty area to focus your final project on. This might be a skill that will be of particular use to you this summer, something you could see helping you in the future, or just an areas where you could see the most positive impact.

### Grades

At the beginning of the class I will ask you to review a skills rubric and assess you current abilities with each featured skill. This might vary a lot over the range of topics, but please be honest - zero experience is a totally acceptable answer: we are not here to judge you, only to help you be successful.

Once you've completed this self-assessment, we will work together to determine an appropriate assessment model on a one-to-one basis. In general, the grading will be as follows

* Core Skills: Self-reflection, abstract, oral presentation - 10 points for completing the activities in each. 5 bonus points for each for showing improvement based on initial revision and self-assessment

* Focus Areas: Literature, data viz, data design, poster making, storytelling - 5 points for each L1 activity correctly completed

* Personal class project: Based on one of the focus areas - up to 25 points for completing meaningful project. 5 points for revision

Total possible points: 100

### Class Times and Your Research Internship

Class will be most Monday mornings. In this period we'll have both synchronous and asynchronous class work. I will be available to you during this time and we expect you to be available for full-class, small group and individual interaction as needed.


## Platforms

To deliver the class content and skills, we will be using the following platforms. I have indicated below which of these you will have to sign-up for.

### Class Site

The site you are reading this on is the class website. It will be where we share the work you will need to complete for each level, module and topic. If a submission is required I will link directly to it in Google Classroom or RStudio Cloud (see below).

### Google Classroom

Google Classroom will be where we organize some assignments and submissions for various assignments. You will need to sign-up for the class with the link and access code I will send to you through Slack.

### Slack

To facilitate direct communication with and between members of the 2024 PEP Cohort, we will be using Slack. This is a direct and group messaging application that will allow us to share news and upcoming events with the whole group as well as organize smaller discussions or contact individual students. You should already have signed-up for a Slack account.

Please contact us through Slack if you have questions or need assistance.

## Resources/Texts

Our general oceanography text will be:

[Introduction to Ocean Sciences](https://www.reefimages.com/oceansci.php), Second digital edition, ver 4.14 by Douglas A. Segar

This is a good introductory text on the many aspects of ocean science and is all [available online](https://www.reefimages.com/oceansci.php) for free. We'll be directing you to readings by chapter number and page. In addition, there is a section called [Critical Concepts](https://www.reefimages.com/oceans/SegarOcean4CritCon.pdf) which covers ideas that span multiple chapters. We will be directing you to review some of those by number also. The chapters all load as PDFs so you might consider saving assigned chapters to your computer and organizing them for future browsing.

For R visualization work, the core text is:

[R for Data Science](https://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham. This is a great intro text to working with data in R. I recommend reading the whole thing over the course of the summer, but I'll be assigning specific chapters in class.

Other readings and resources for the class will be distributed as required. 




