---
title: 'Advanced Poster Design'
author: Ben Harden
date: '2021-05-05'
level: 3
slug: []
categories: []
tags: []
draft: yes
quiz: https://classroom.google.com/c/NjEyOTIyMzMyOTk2/a/NjEyOTIyMzMzMDYz/details
---

If you are aiming for Level 3 at advanced poster design, your goal is to move from "yeah, that'll do", to "Wow, that's really crisp". As such my main criteria for determining whether you have reached this goal will be a close scrutiny of your poster elements to make sure that they really are consistent and appropriate.

I will not be looking at content, only at design. I'll be mainly looking at:

* How well your images/figures are displayed - are they cropped and aligned well?
* What colors you used and whether there is consistency and contrast throughout your poster
* Whether the fonts are consistent and appropriate and if text boxes are well-aligned
* The balance of white space in the poster and other spacing

I will make sure I give you one round of specific feedback to review in the poster making process. I want to encourage you to be bold and experiment. I'm not looking for perfect, only creativity and a deliberate attention to detail.

As such, I'd also like to hear from you after the poster is completed. Please submit a one page (double-spaced, 12pt) reflection on your poster to the assignment below including:

* What design elements you included and what you think they are effective.
* What elements didn't work as you had intended and how might you do them differently
* What your main takeaways will be for doing this work again in the future

