---
title: "Personal Reflections"
author: Ben Harden
date: '2021-05-05'
level: 1
slug: []
categories: []
tags: []
draft: no
---

Throughout the class period, I'm going to be asking you to reflect on what you are learning/experiencing in a few ways. Self reflection is important as you grow in your careers. It will help you:

* Understand what you are learning and why you are learning it
* Highlight your strengths and weaknesses 
* Determine what career path is right for you
* Ensure you are being a helpful collaborator
* Build self esteem
* Become more creative
* And many many more things...

The goal of this section is to expose or remind you of some possible helpful strategies and practice some of them to help us understand where we are and where we are going.

Some of the strategies we can use (and not all of them we will use) are:

* [Freewriting](https://writingprocess.mit.edu/process/step-1-generate-ideas/instructions/freewriting)
* Sketching
* [Morning Pages](https://www.chriswinfield.com/morning-pages/)
* [Mind Mapping](https://en.wikipedia.org/wiki/Mind_map)
* Reflection Buddy: Talking about a question with a peer
* [Vlogging](https://en.wikipedia.org/wiki/Vlog) or [audio journals](https://www.journalinghabit.com/guide-to-keeping-an-audio-journal/), but not necessarily for the public.

In addition to the self reflection, we will also be hearing from a variety of Woods Hole researchers on their work and their path to science in the Village. Your self reflections, the conversations with the guest researchers, and other interactions that you are having during your time in Woods Hole will form the basis for an email you're going to write in Level 2.