---
title: Todo List
author: Ben Harden
date: '2023-06-04'
slug: []
categories: []
tags: []
draft: no
---

Here is the todo list from the most recent classes:

## Class: Mon July 15

1. Look for the DMs on Slack about your personal class project - I should have given you all some idea of what I am look for you to have completed by the next class (Mon July 22). We will use some of the class time to review where you are at and set goals for next week. We have about three weeks to work on these projects and getting a little bit done each week and getting feedback from me will help you build those skills

1. Complete the [R level 1](/classes/focus-areas/data-viz/level-1) and [Data Design Level 1](/classes/focus-areas/data-design/level-1) if you haven't already


## Class: Mon July 8

1. Redesign a figure from a research paper you've read as described in [Level 1 of Data Design](/classes/focus-areas/data-design/level-1)

1. Reading for the final focus area topic on Storytelling. Go to [Level 1](/classes/focus-areas/storytelling/level-1), read the required sections of the document there and complete the short reflection. We will be sharing these reflections at the start of the next class.

1. Its time to confirm what your focus area goals are going to be - look for a DM from me so we can make a provisional plan to confirm during class on Monday.

1. If you haven't completed the [Level 1 of the intro to R](/classes/focus-areas/data-viz/level-1) then do that ASAP - there's much to do so let's make sure we're staying on track.

## Class: Mon June 31

1. Log on to the [class Google Classroom](https://classroom.google.com/c/NjgxMDE4NDM5Mzky?cjc=k2upqgn) - this will help me organize your submissions for various things you are doing.

1. Complete [Level 1 of the intro to R](/classes/focus-areas/data-viz/level-1) and submit to the [Google Classroom assignment](https://classroom.google.com/c/NjgxMDE4NDM5Mzky?cjc=k2upqgn) (link on the level 1 page too). Let me know if you need additional input - if you are still having trouble, that is fine, I'll check in with you during the next class.

1. Read the content on the following pages

+ [Level 1: Data Design](/classes/focus-areas/data-design/level-1)
+ [Level 1: Research Poster](/classes/focus-areas/poster/level-1) 

There is a good amount of overlap between these two readings as they are both essentially about design so I thought we'd cover them at the same time. We'll be doing some discussions about the content in these at the start of next class so make sure you're familiar with these ideas. 

## Class: Mon June 24

You have two things to do this week - get you presentations ready and prepare some work for thinking about using R for data visualization.

1. Prepare your mid-term research presentation

Remember, your presentation should be between 5-7 mins (no longer)

Your audience is your PEP peers and you goal is to give a clear, concise and compelling introduction to your summer research.

Use the information posted in the [level 1](/classes/core-skills/presentation/level-1) to begin putting together your ideas and slides for your presentation. If you already feel confident in your scientific presentations then you should also check out content in [level 2](/classes/core-skills/presentation/level-2) and [level 3](/classes/core-skills/presentation/level-3) to help build your skills

Ideally, you should prepare your presentation slides in Google Slides. Regardless, you should share your slides with Autumn, no later than 9pm on Sunday evening (June 30) so we have time to put them together 

Please DM me if you have questions or want me to check anything ahead of time

I'll be using this presentation to get a sense of where you're at so I can help you level up your skills ahead of your final presentation in August.

2. In addition to completing your presentation prep, I want to get us started thinking about using R for data visualization - remember you'll be exposed to all the focus areas. 

Go to the [level 1 page for Coding for Visualization](/classes/focus-areas/data-viz/level-1) and complete the reading and R orientation exercises. 








## Class: Fri June 14

1. Complete your self-assessment using the [Skills Rubric](/docs/pep2024_rubric.pdf). Discuss this with your mentor to help you determine which focus areas you want to work on.
1. Complete this ["Getting to Know you" survey](https://docs.google.com/forms/d/e/1FAIpQLSdqKHCQmCD4S640-ayeZ0jZiGce4K_ITpHUlEygV_fz6FZ1cQ/viewform?usp=sf_link)

1. Get a research paper from your mentor and complete the following short exercise using the resources on the [classes](/classes) page as needed:

* Decide on the reason you are reading this research paper
* Tell me which paper sections you therefor are focusing your energy
* Describe in a few sentences what you learnt in relation to your reason for reading
