---
title: "Intro to Data Design"
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 1
slug: []
categories: []
tags: []
draft: no
---

In this section, we're going to explore some ideas behind effective data design and then implement them in R.

Data design is all about the choices you make in presenting your data that affect how effective your graphic tells stories in your data. This includes deciding what variables to plot, how they are represented on the graph (lines, points, smoothing, etc.), what other supporting information to show (grid lines, axes), and what colors/line-strengths to use in all of your imagery.

## Reading 

We're going to begin in this level by reading some background theory on effective data design. You should read through the following as a primer on some considerations for how and what to plot:

* Read through [Chapter One](https://socviz.co/lookatdata.html#lookatdata) of Kieran Healy's Book *Data Visualization: A practical introduction*. This section talks about some basics of good visualization and some common pitfalls. The rest of the book is a practical guide to using R to make compelling graphics so a great resources for the rest of the class in general.

* Read [this chapter](04data-ink_graphical-redesign.pdf) of Edward R. Tufte's classic work "The Visual Display of Quantitative Information". In this chapter, Tufte talks about one of his most famous ideas - maximizing the data-ink ratio (within reason).