---
title: 'More R Tools'
author: Ben Harden
date: '2021-05-05'
level: 3
slug: []
categories: []
tags: []
draft: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Now that you're familiar with a few different R tools for plotting well formatted data, you can push your skills forward in many directions. 

You should look into the following R skills and decide which might be interesting to add to your data visualization toolkit

* [Processing data](https://r4ds.hadley.nz/data-tidy): Learn how to create tidy data from poorly formatted data or data from an [Excel spreadsheet](https://r4ds.hadley.nz/spreadsheets). Almost all data that you will be given at some point will need some processing and tidying to make it usable with ggplot so you'll need to have some of these. You may also need to know how to manipulate words ([string](https://r4ds.hadley.nz/strings)) in data too.

* [Reporting data in Quatro](https://r4ds.hadley.nz/quarto)(previously RMarkdown): This is a way to combine your code, figures and text in one document. I use it make pdfs, presentations and even this website.

* [Creating web maps using leaflet](https://rstudio.github.io/leaflet/): I use this a bunch for making data rich websites (e.g. as the basis for [this plastics data maps](https://seaplasticviz.netlify.app/plastic-vis/)) and it's just a fun tool to play with

* [Interactive visualizations with shiny](https://shiny.posit.co/): Also an interesting tool more for communication than anything else, but will help you understand how visualizations can be used to help people explore a topic.

* [Other things?](https://r4ds.hadley.nz/): This book is full of ways that you can move your R work forward. Take a quick look at the contents on the left to see if anything stands out to you.