---
title: "Science Storytelling"
author: Ben Harden
date: '2021-05-05'
level: 1
slug: []
categories: []
tags: []
draft: no
---

You may find yourself in many scenarios when you will find yourself talking about your science to a general audience. When you do, it'll be important to modify how you present information compared to how you would to a scientific colleague. In addition to language shifts you'll also need to consider how to make your work sound interesting and relevant. Much of that can be achieved through the art of science storytelling.

## Reading

There are tons of places to learn about what kinds of shifts in communication strategy you need to make to communicate with a general audience.

Start by reading the Foreword (pg 1) and the sections on "Crafting your message" (pg 21-44) and "Overcoming Barriers" (just subsection 7, pg 45-55) in [Connecting on Climate: A Guide for Effective Climate Change Communication](ecoAmerica-CRED-2014-Connecting-on-Climate.pdf) by 
The Center for Research on Environmental Decisions (CRED) at The Earth Institute, Columbia University, and ecoAmerica, a climate solutions nonprofit.

This document talks about Climate Change in particular, but I think it more broadly talks about how to connect some of the topics you might want to talk about with a target audience.

Take notes on what speaks to you most about how to communicate important scientific topics to a general audience.

## Homework

Think about the research you are doing this summer. Now think about a family member or friend who is outside of science. Use what the above reading to answer he following:

1. Which *two tips* that you read about in the reading would help you communicate your science with this audience and why?
2. Write one/two sentence(s) that you could hear yourself saying to this audience that you think would be an effective way to implement the ideas in one of the tips you have chosen.